#!/bin/bash
set -e
case $1 in
  "compile")
    cargo run -- build -i playground
    unzip -o playground/playground.sb3 project.json -d playground
    python -m json.tool --indent 4 playground/project.json playground/project.json
    node tools/sb3.js playground/project.json
    ;;
  "uncompile")
    unzip -o playground/playground.sb3 project.json -d playground
    python -m json.tool --indent 4 playground/project.json playground/project.json
    node tools/sb3.js playground/project.json
    ;;
  "patch")
    node tools/sb3.js playground/project.json
    zip -ur playground/playground.sb3 playground/project.json
    ;;
  "check")
    zip -ur "$2" TMP
    node tools/sb3.js TMP
    rm TMP
    ;;
  *)
    echo "Usage: tools/run {compile|uncompile|patch|check}"
    exit 1
    ;;
esac
