name: check
on: [pull_request, workflow_dispatch]
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  rustflags: "-A warnings"
            - run: cargo check
            - run: cargo test
