start: declr*

declr: "costumes" _stringlist ";" -> declr_costumes
     | NAME stack                 -> declr_hat

stack: "{" block* "}"

block: "if" expr stack -> block_if
     | NAME _exprlist ";"

expr: "(" expr ")"
    | NAME | STRING
    | NAME "(" _exprlist ")" -> reporter

_exprlist: [expr ("," expr)*]
_stringlist: [STRING ("," STRING)*]
_namelist: [NAME ("," NAME)*]

NAME: /[_a-zA-Z][_a-zA-Z0-9]*/
STRING: /"([^"\\]|\\.)*"/

%ignore " "
%ignore "\n"
%ignore "\t"
